spring.application.name=bt-hrm-api
server.port=9020

# Spring security
spring.security.user.name=bktlsurvey
spring.security.user.password=${SPRING_SECURITY_PASSWORD}
spring.security.user.role=MYTH
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/d6c87e53-ad31-4ba6-8520-9e8a406e9b21/v2.0


######################################################
# Database
######################################################
spring.jpa.properties.hibernate.format_sql=false
spring.datasource.url=jdbc:sqlserver://${DB_ENDPOINT}:${DB_PORT};encrypt=true;trustServerCertificate=true;databaseName=${DB_CENTRA}
spring.datasource.username=${DB_ACCOUNT}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=${DB_HRIS_SCHEMA:hris}
spring.jpa.show-sql=${SQL_PREVIEW}
spring.jpa.open-in-view=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

######################################################
# Key Vault
######################################################
spring.cloud.azure.keyvault.secret.endpoint=${KV_SECRET_ENDPOINT}
keyvault.public.key=${KV_PUB_KEY}
keyvault.private.key=${KV_PRI_KEY}


######################################################
# Encrypt Decrypt
######################################################
text.salt.key=${TEXT_SALT_KEY}
text.iv.spec=${TEXT_IV_SPEC}

######################################################
# INTERNAL Endpoint
######################################################
bt.centra.api.endpoint=${CENTRA_PORTAL_ENDPOINT}
bt.hris.storage.blob.container-name=${HRIS_BLOB_CONTAINER:hris}
bt.hris.storage.blob.connection-string=${HRIS_BLOB_CONNECTION_STRING:}
bt.hris.storage.blob.endpoint=${HRIS_BLOB_ENDPOINT:}

#####################################################
#Actuator
######################################################
info.app.name=@project.name@
info.app.version=@project.version@
management.endpoints.web.exposure.include=health,info
management.endpoint.info.show-details=always
management.info.env.enabled=true
